#!/bin/bash
# Checks for running services, both systemd and docker containers
# Specific for hjorne-skap
printf '\n'

# Check if the specified containers are running
dockercont=( unifi ) #resilio dropbox 
#docker container ls --format "table {{.Names}}\t{{.CreatedAt}}\t{{.Status}}"
for i in "${dockercont[@]}"; do
  if docker ps | grep --quiet -i $i; then
    printf '%-24srunning\n' "$i"
  else
    printf '%-24sNOT RUNNING!\n' "$i"
  fi
done

# Check if the specified services are running
services=( smbd.service docker.service syncthing@syncthing )
for i in "${services[@]}"; do
  printf '%-24s%s\n' "$i" "$(systemctl is-active $i)"
done

# Check if data in folders have changed in the last 72 (4320min). 
syncedFolders=( "/media/pool/docker/syncthing/Sleep As Android/" \
                "/media/pool/docker/syncthing/Signal backups/" \
                "/media/pool/media/pictures/phone/syncthing/DCIM/" \
                "/media/pool/media/audio/music/syncthing/GMMP/" )
for i in "${syncedFolders[@]}"; do
  if [[ ! $(find "$i" -cmin -4320 -type f) ]]; then
    printf '%-24sNOT changed in 24h!\n' "$(basename "$i")"
  else
    printf '%-24sOk\n' "$(basename "$i")"
  fi
done

# Uses only first UPS
nut_ups=$(upsc -l 2>/dev/null | awk '{ print $1 }')
ups_mfr=$(upsc ${nut_ups} ups.mfr 2>&1 | grep --invert-match '^Init SSL')
ups_mode=$(upsc ${nut_ups} ups.model 2>&1 | grep --invert-match '^Init SSL')
ups_charge=$(upsc ${nut_ups} battery.charge 2>&1 | grep --invert-match '^Init SSL')
#printf '%s %s: %s%% battery\n' "$ups_mfr" "$ups_mode" "$ups_charge"
printf '\n%-24s%s%% battery\n' "$ups_mfr $ups_mode: " "$ups_charge"
if ! upsc $nut_ups ups.status 2>/dev/null | grep --quiet OL; then
  printf '#################\n# ON BATTERY!!! #\n#################\n'
fi
